#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

# Copyright (c) 2005-2014 Fpemud <fpemud@sina.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import os
import sys
import strict_hdds


def usage():
    print('Usage:')
    print('   strict_hdds show <directory>')
    print('   strict_hdds mount <directory> [--layout-name=name] [--disk-list=dev1,dev2...] [--read-only] [--extra-mount-options-for-rootfs=opt1,opt2...] [--extra-mount-options-for-boot=opt1,opt2...]')
    print('   strict_hdds create-and-mount <directory> <layout-name> [--disk-list=dev1,dev2...] [--read-only] [--extra-mount-options-for-rootfs=opt1,opt2...] [--extra-mount-options-for-boot=opt1,opt2...]')
    print('   strict_hdds add-harddisk <directory> <devpath>')
    print('   strict_hdds remove-harddisk <directory> <devpath>')
    print('   strict_hdds create-swap-file <directory>')
    print('   strict_hdds remove-swap-file <directory>')
    print('   strict_hdds create-snapshot <directory> <snapshot-name>')
    print('   strict_hdds remove-snapshot <directory> <snapshot-name>')
    print('   strict_hdds sync-from-snapshot <directory> <snapshot-name> [--sync-home] [--sync-var]')
    print('   strict_hdds check <directory>')
    print('   strict_hdds umount <directory>')
    print('')
    print('Supported layout:')
    for layoutName in strict_hdds.get_supported_storage_layout_names():
        print('   %s' % (layoutName))
    print('')


def die(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def doShow():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    layout = strict_hdds.get_storage_layout(sys.argv[2])
    _show(layout)


def doMount():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    kwargs = dict()
    for x in sys.argv[3:]:
        if x.startswith("--layout-name="):
            kwargs["layout_name"] = x[len("--layout-name="):]
        if x.startswith("--disk-list="):
            kwargs["disk_list"] = x[len("--disk-list="):].split(",")
        if x == "--read-only":
            kwargs["read_only"] = True
        if x.startswith("--extra-mount-options-for-rootfs="):
            kwargs["extra_mount_point_for_rootfs"] = x[len("--extra-mount-options-for-rootfs="):]
        if x.startswith("--extra-mount-options-for-boot="):
            kwargs["extra_mount_point_for_boot"] = x[len("--extra-mount-options-for-boot="):]
    layout = strict_hdds.mount_storage_layout(sys.argv[2], **kwargs)
    _show(layout)


def doCreateAndMount():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    if len(sys.argv) < 4:
        die("No storage layout name specified!")
    kwargs = dict()
    for x in sys.argv[4:]:
        if x.startswith("--disk-list="):
            kwargs["disk_list"] = x[len("--disk-list="):].split(",")
        if x == "--read-only":
            kwargs["read_only"] = True
        if x.startswith("--extra-mount-options-for-rootfs="):
            kwargs["extra_mount_point_for_rootfs"] = x[len("--extra-mount-options-for-rootfs="):]
        if x.startswith("--extra-mount-options-for-boot="):
            kwargs["extra_mount_point_for_boot"] = x[len("--extra-mount-options-for-boot="):]
    layout = strict_hdds.create_and_mount_storage_layout(sys.argv[3], sys.argv[2], **kwargs)
    _show(layout)


def doAddHarddisk():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    if len(sys.argv) < 4:
        die("No harddisk device file specified!")
    layout = strict_hdds.get_storage_layout(sys.argv[2])
    if not hasattr(layout, "add_disk"):
        die("Operation is not supported by layout \"%s\"." % (layout.name))
    layout.add_disk(sys.argv[3])


def doRemoveHarddisk():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    if len(sys.argv) < 4:
        die("No harddisk device file specified!")
    layout = strict_hdds.get_storage_layout(sys.argv[2])
    if not hasattr(layout, "remove_disk"):
        die("Operation is not supported by storage layout \"%s\"." % (layout.name))
    layout.remove_disk(sys.argv[3])


def doCreateSwapFile():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    layout = strict_hdds.get_storage_layout(sys.argv[2])
    if not hasattr(layout, "create_swap_file"):
        die("Operation is not supported by layout \"%s\"." % (layout.name))
    layout.create_swap_file()


def doRemoveSwapFile():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    layout = strict_hdds.get_storage_layout(sys.argv[2])
    if not hasattr(layout, "remove_swap_file"):
        die("Operation is not supported by layout \"%s\"." % (layout.name))
    layout.remove_swap_file()


def doCreateSnapshot():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    if len(sys.argv) < 4:
        die("No snapshot name specified!")
    layout = strict_hdds.get_storage_layout(sys.argv[2])
    if not hasattr(layout, "create_snapshot"):
        die("Operation is not supported by layout \"%s\"." % (layout.name))
    layout.create_snapshot(sys.argv[3])


def doRemoveSnapshot():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    if len(sys.argv) < 4:
        die("No snapshot name specified!")
    layout = strict_hdds.get_storage_layout(sys.argv[2])
    if not hasattr(layout, "remove_snapshot"):
        die("Operation is not supported by layout \"%s\"." % (layout.name))
    layout.remove_snapshot(sys.argv[3])


def doSyncFromSnapshot():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    if len(sys.argv) < 4:
        die("No snapshot name specified!")
    kwargs = dict()
    for x in sys.argv[4:]:
        if x == "--sync-home":
            kwargs["home"] = True
        if x == "--sync-var":
            kwargs["var"] = True
    layout = strict_hdds.get_storage_layout(sys.argv[2])
    if not hasattr(layout, "rollback_to_snapshot"):
        die("Operation is not supported by layout \"%s\"." % (layout.name))
    layout.rollback_to_snapshot(sys.argv[3], **kwargs)


def doCheck():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    def __errCb(checkCode, message):
        print(message)
    layout = strict_hdds.get_storage_layout(sys.argv[2])
    layout.check(False, __errCb)
    if layout.name in ["bios-ext4", "efi-ext4", "efi-bcache-btrfs", "efi-bcachefs"]:
        layout.opt_check("swap", False, __errCb)
    if layout.name == "efi-bcache-btrfs":
        layout.opt_check("bcache-write-mode", "writeback", False, __errCb)


def doUmount():
    if len(sys.argv) < 3:
        die("No mount point directory specified!")
    layout = strict_hdds.get_storage_layout(sys.argv[2])
    layout.umount_and_dispose()


def _show(layout):
    if layout is None:
        print("Storage layout: empty")
        return

    if layout.name == "efi-bcachefs":
        if layout.get_ssd() is not None:
            ssdStr = layout.get_ssd()
            if layout.get_ssd_swap_partition() is not None:
                swapStr = "(with swap)"
            else:
                swapStr = ""
            bootDiskStr = ""
        else:
            ssdStr = "None"
            swapStr = ""
            bootDiskStr = " (boot disk: %s)" % (layout.boot_disk)
        print("Storage layout: %s, SSD: %s%s, HDDs: %s%s" % (layout.name, ssdStr, swapStr, " ".join(layout.get_hdd_list()), bootDiskStr))
        return

    if layout.name == "efi-bcache-btrfs":
        if layout.get_ssd() is not None:
            ssdStr = layout.get_ssd()
            if layout.get_ssd_swap_partition() is not None:
                swapStr = "(with swap)"
            else:
                swapStr = ""
            bootDiskStr = ""
        else:
            ssdStr = "None"
            swapStr = ""
            bootDiskStr = " (boot disk: %s)" % (layout.boot_disk)
        print("Storage layout: %s, SSD: %s%s, HDDs: %s%s" % (layout.name, ssdStr, swapStr, " ".join(layout.get_hdd_list()), bootDiskStr))
        return

    if layout.name == "efi-btrfs":
        if layout.get_ssd() is not None:
            bootDiskStr = ""
        else:
            bootDiskStr = " (boot disk: %s)" % (layout.boot_disk)
        print("Storage layout: %s, HDDs: %s%s" % (layout.name, " ".join(layout.get_hdd_list()), bootDiskStr))
        return

    if layout.name == "efi-ext4":
        if layout.dev_swap is not None:
            swapStr = " (with swap)"
        else:
            swapStr = ""
        print("Storage layout: %s, HDD: %s%s" % (layout.name, layout.boot_disk, swapStr))
        return

    if layout.name == "bios-ext4":
        if layout.dev_swap is not None:
            swapStr = " (with swap)"
        else:
            swapStr = ""
        print("Storage layout: %s, HDD: %s%s" % (layout.name, layout.boot_disk, swapStr))
        return

    assert False


if __name__ == '__main__':
    if len(sys.argv) <= 1:
        usage()
        sys.exit(1)

    if sys.argv[1] == "--help":
        usage()
        sys.exit(0)

    if os.getuid() != 0:
        die("You must run this command as root!")

    op = sys.argv[1]
    if op == "show":
        doShow()
    elif op == "mount":
        doMount()
    elif op == "create-and-mount":
        doCreateAndMount()
    elif op == "add-harddisk":
        doAddHarddisk()
    elif op == "remove-harddisk":
        doRemoveHarddisk()
    elif op == "create-swap-file":
        doCreateSwapFile()
    elif op == "remove-swap-file":
        doRemoveSwapFile()
    elif op == "create-snapshot":
        doCreateSnapshot()
    elif op == "remove-snapshot":
        doRemoveSnapshot()
    elif op == "sync-from-snapshot":
        doSyncFromSnapshot()
    elif op == "check":
        doCheck()
    elif op == "umount":
        doUmount()
    else:
        die('Invalid operation.')
