#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

# Copyright (c) 2005-2014 Fpemud <fpemud@sina.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import sys
import strict_hdds


def usage():
    print('Usage:\n')
    print('   strict_hdds show                           show current storage layout\n')
    print('   strict_hdds create-and-mount <directory>   create storage layout and mount it to the specified directory\n')
    print('   strict_hdds detect-and-mount <directory>   detect storage layout and mount it to the specified directory\n')
    print('   strict_hdds add-harddisk <devpath>         add a harddisk into current storage layout\n')
    print('   strict_hdds remove-harddisk <devpath>      remove a harddisk from current storage layout\n')
    print('   strict_hdds enable-swap                    enable swap for current storage layout\n')
    print('   strict_hdds disable-swap                   disable swap for current storage layout\n')
    print('   strict_hdds umount                         umount current storage layout\n')
    print('\n')
    print('Supported layout:\n')
    for layoutName in strict_hdds.get_supported_storage_layout_names():
        print('   %s\n' % (layoutName))
    print('\n')


def die(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


if __name__ == '__main__':
    c = 1
    op = None

    if len(sys.argv) <= c:
        usage()
        sys.exit(1)

    if sys.argv[c] == "--help":
        usage()
        sys.exit(0)

    op = sys.argv[c]
    if op == "show":
        pass
    elif op == "create-and-mount":
        c += 1
        targetDir = None
    elif op == "detect-and-mount":
        targetDir = None
    elif op == "add-harddisk":
        pass
    elif op == "remove-harddisk":
        pass
    elif op == "enable-swap":
        pass
    elif op == "disable-swap":
        pass
    elif op == "umount":
        pass
    else:
        die('Invalid operation.')

    while len(sys.argv) > c:
        if destDir is not None:
            die("No argument should exists after <dest-dir>.")

        if sys.argv[c] == "--force":
            bForce = True
            c += 1
            continue

        if sys.argv[c] == "--create-subdir":
            bCreateSubDir = True
            c += 1
            continue

        if sys.argv[c] == "--all":
            if len(productIdList) > 0:
                die("--all and --product are mutally exclusive.")
            bAll = True
            c += 1
            continue

        if sys.argv[c] == "--product":
            c += 1
            if len(sys.argv) <= c:
                die('Missing product id.')
            productId = sys.argv[c]
            if productId in productIdList:
                die("Duplicate product id %s specified." % (productId))
            if productId not in windown.WindowsDownloader.get_product_id_list():
                die("Invalid product id %s." % (productId))
            if bAll:
                die("--all and --product are mutally exclusive.")
            productIdList.append(productId)
            c += 1
            continue

        destDir = sys.argv[c]
        c += 1

    if destDir is None:
        die('No destination directory specified.')

    if op == "windows":
        downloadWindows(bForce, bCreateSubDir, destDir, bAll, productIdList)
    elif op == "office":
        downloadOffice()
    else:
        assert False



class Main:

    def main(self):
        if os.getuid() != 0:
            print("You must run this command as root!")
            return 1

        self.args = self._getArgParser().parse_args()

        if not hasattr(self.args, "op") or self.args.op == "show":
            layout = strict_hdds.get_storage_layout("/mnt/gentoo")
            return self._show(layout)

        if self.args.op == "detect-and-mount":
            kwargs = dict()
            if self.args.read_only is not None:
                kwargs["read_only"] = self.args.read_only
            if self.args.extra_mount_options is not None:
                kwargs["extra_mount_point_for_rootfs"] = self.args.extra_mount_options
            layout = strict_hdds.detect_and_mount_storage_layout("/mnt/gentoo", **kwargs)
            return self._show(layout)

        if self.args.op == "create-and-mount":
            if self.args.layout_name not in strict_hdds.get_supported_storage_layout_names():
                print("Invalid storage layout!")
                return 1
            layout = strict_hdds.create_and_mount_storage_layout(self.args.layout_name, "/mnt/gentoo")
            return self._show(layout)

        if self.args.op == "wipe":
            _Util.wipeHarddisk(self.args.harddisk)
            return 0

        if self.args.op == "wipe-all":
            for devpath in _Util.getDevPathListForFixedHdd():
                print("Wipe harddisk %s" % (devpath))
                _Util.wipeHarddisk(devpath)
            return 0

        assert False

    def _getArgParser(self):
        parser = argparse.ArgumentParser()
        subparsers = parser.add_subparsers()

        parser2 = subparsers.add_parser("show", help="Show target storage information")
        parser2.set_defaults(op="show")

        parser2 = subparsers.add_parser("detect-and-mount", help="Auto detect storage layout and mount it")
        parser2.set_defaults(op="detect-and-mount")
        parser2.add_argument("--read-only", action="store_true")
        parser2.add_argument("--extra-mount-options")

        parser2 = subparsers.add_parser("create-and-mount", help="Create new target storage layout and mount it")
        parser2.set_defaults(op="create-and-mount")
        parser2.add_argument("layout_name", metavar="layout-name")

        parser2 = subparsers.add_parser("wipe-harddisk", help="Wipe the specified harddisk")
        parser2.set_defaults(op="wipe")
        parser2.add_argument("harddisk")

        parser2 = subparsers.add_parser("wipe-all-harddisks", help="Wipe all the harddisks of target storage")
        parser2.set_defaults(op="wipe-all")

        return parser

    def _show(self, layout):
        # FIXME: show read-only

        if layout is None:
            print("Storage layout: empty")
            return 1

        if layout.name == "efi-bcachefs":
            if layout.get_ssd() is not None:
                ssdStr = layout.get_ssd()
                if layout.get_ssd_swap_partition() is not None:
                    swapStr = "(with swap)"
                else:
                    swapStr = ""
                bootDiskStr = ""
            else:
                ssdStr = "None"
                swapStr = ""
                bootDiskStr = " (boot disk: %s)" % (layout.boot_disk)
            print("Storage layout: %s, SSD: %s%s, HDDs: %s%s" % (layout.name, ssdStr, swapStr, " ".join(layout.get_hdd_list()), bootDiskStr))
            return 0

        if layout.name == "efi-bcache-btrfs":
            if layout.get_ssd() is not None:
                ssdStr = layout.get_ssd()
                if layout.get_ssd_swap_partition() is not None:
                    swapStr = "(with swap)"
                else:
                    swapStr = ""
                bootDiskStr = ""
            else:
                ssdStr = "None"
                swapStr = ""
                bootDiskStr = " (boot disk: %s)" % (layout.boot_disk)
            print("Storage layout: %s, SSD: %s%s, HDDs: %s%s" % (layout.name, ssdStr, swapStr, " ".join(layout.get_hdd_list()), bootDiskStr))
            return 0

        if layout.name == "efi-btrfs":
            if layout.get_ssd() is not None:
                bootDiskStr = ""
            else:
                bootDiskStr = " (boot disk: %s)" % (layout.boot_disk)
            print("Storage layout: %s, HDDs: %s%s" % (layout.name, " ".join(layout.get_hdd_list()), bootDiskStr))
            return 0

        if layout.name == "efi-ext4":
            if layout.dev_swap is not None:
                swapStr = " (with swap)"
            else:
                swapStr = ""
            print("Storage layout: %s, HDD: %s%s" % (layout.name, layout.boot_disk, swapStr))
            return 0

        if layout.name == "bios-ext4":
            if layout.dev_swap is not None:
                swapStr = " (with swap)"
            else:
                swapStr = ""
            print("Storage layout: %s, HDD: %s%s" % (layout.name, layout.boot_disk, swapStr))
            return 0

        assert False

    # deprecated
    def _createAndMount(self):
        if self.args.layout_name not in strict_hdds.get_supported_storage_layout_names():
            print("Invalid storage layout!")
            return 1

        layout = strict_hdds.create_and_mount_storage_layout(self.args.layout_name, "/mnt/gentoo")
        if self.args.layout_name == "bios-ext4":
            print("Root device: %s" % (layout.dev_rootfs))
            print("Swap file: None")
        elif self.args.layout_name == "efi-ext4":
            print("Root device: %s" % (layout.dev_rootfs))
            print("Swap file: None")
        elif self.args.layout_name == "efi-btrfs":
            print("Root device: %s" % (layout.dev_rootfs))
        elif self.args.layout_name == "efi-bache-btrfs":
            print("Root device: %s" % (layout.dev_rootfs))
            print("Swap device: %s" % (layout.dev_swap if layout.dev_swap is not None else "None"))
            print("Boot disk: %s" % (layout.get_esp()))
        elif self.args.layout_name == "efi-bcachefs":
            print("Root device: %s" % (layout.dev_rootfs))
            print("Swap device: %s" % (layout.dev_swap if layout.dev_swap is not None else "None"))
            print("Boot disk: %s" % (layout.get_esp()))
        else:
            assert False
        return 0


class _Util:

    @staticmethod
    def cmdCall(cmd, *kargs):
        # call command to execute backstage job
        #
        # scenario 1, process group receives SIGTERM, SIGINT and SIGHUP:
        #   * callee must auto-terminate, and cause no side-effect
        #   * caller must be terminated by signal, not by detecting child-process failure
        # scenario 2, caller receives SIGTERM, SIGINT, SIGHUP:
        #   * caller is terminated by signal, and NOT notify callee
        #   * callee must auto-terminate, and cause no side-effect, after caller is terminated
        # scenario 3, callee receives SIGTERM, SIGINT, SIGHUP:
        #   * caller detects child-process failure and do appopriate treatment

        ret = subprocess.run([cmd] + list(kargs),
                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                             universal_newlines=True)
        if ret.returncode > 128:
            # for scenario 1, caller's signal handler has the oppotunity to get executed during sleep
            time.sleep(1.0)
        if ret.returncode != 0:
            print(ret.stdout)
            ret.check_returncode()
        return ret.stdout.rstrip()

    @staticmethod
    def wipeHarddisk(devpath):
        with open(devpath, 'wb') as f:
            f.write(bytearray(1024))

    @staticmethod
    def getDevPathListForFixedHdd():
        ret = []
        for line in _Util.cmdCall("/bin/lsblk", "-o", "NAME,TYPE", "-n").split("\n"):
            m = re.fullmatch("(\\S+)\\s+(\\S+)", line)
            if m is None:
                continue
            if m.group(2) != "disk":
                continue
            if re.search("/usb[0-9]+/", os.path.realpath("/sys/block/%s/device" % (m.group(1)))) is not None:      # USB device
                continue
            ret.append("/dev/" + m.group(1))
        return ret


###############################################################################


if __name__ == "__main__":
    ret = Main().main()
    sys.exit(ret)
